next:
  container_name: next-starter-kit
  image: mhart/alpine-node
  ports:
    - "3000:3000"
    - "8090:8090"
  volumes:
    - .:/app
    - ./logs:/app/logs
  working_dir: /app
  command: ["npm", "run", "dev"]
